begin;

-- =========================================================
-- 0) HELPER FUNCTIONS
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =========================================================
-- 1) CORE PROFILE / BUILDING
-- =========================================================

create table public.ho_so (
  ma_ho_so bigint generated by default as identity primary key,
  ma_nguoi_dung_xac_thuc uuid unique references auth.users(id) on delete set null,
  vai_tro varchar(50) not null default 'KHACH_HANG',
  ho_ten varchar(150),
  email varchar(255) unique,
  so_dien_thoai varchar(20),
  dia_chi_thuong_tru text,
  avatar_url text,
  ngan_hang_ten varchar(100),
  ngan_hang_so_tai_khoan varchar(50),
  ngan_hang_chu_tai_khoan varchar(150),
  so_cccd varchar(20),
  ngay_cap_cccd date,
  cccd_mat_truoc_url text,
  cccd_mat_sau_url text,
  lien_he_khan_cap_ho_ten varchar(150),
  lien_he_khan_cap_sdt varchar(20),
  lien_he_khan_cap_moi_quan_he varchar(50),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.toa (
  ma_toa bigint generated by default as identity primary key,
  ma_dinh_danh varchar(100) not null unique,
  ten varchar(255) not null,
  dia_chi text,
  quan_huyen varchar(100),
  thanh_pho varchar(100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tang (
  ma_tang bigint generated by default as identity primary key,
  ma_toa bigint not null references public.toa(ma_toa) on delete cascade,
  so_tang integer not null,
  ten_tang varchar(100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_tang_toa_so_tang unique (ma_toa, so_tang)
);

create type public.gioi_tinh_type as enum ('Nam', 'Nữ', 'Nam/Nữ');
create table public.phong (
  ma_phong bigint generated by default as identity primary key,
  ma_toa bigint not null references public.toa(ma_toa) on delete restrict,
  ma_tang bigint not null references public.tang(ma_tang) on delete restrict,
  ma_phong_hien_thi varchar(50) not null,
  loai_phong varchar(50) not null,
  suc_chua integer not null default 0 check (suc_chua >= 0),
  gia_thang numeric(14,2) not null default 0 check (gia_thang >= 0),
  trang_thai varchar(50) not null default 'TRONG',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_phong_toa_ma_hien_thi unique (ma_toa, ma_phong_hien_thi)
);

alter table public.phong 
add column if not exists gioi_tinh public.gioi_tinh_type default 'Nam/Nữ';

create table public.giuong (
  ma_giuong bigint generated by default as identity primary key,
  ma_phong bigint not null references public.phong(ma_phong) on delete cascade,
  ma_giuong_hien_thi varchar(50) not null,
  nhan_giuong varchar(50),
  gia_thang numeric(14,2) not null default 0 check (gia_thang >= 0),
  trang_thai varchar(50) not null default 'TRONG',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_giuong_phong_ma_hien_thi unique (ma_phong, ma_giuong_hien_thi)
);

create table public.hinh_anh_phong (
  ma_hinh_anh bigint generated by default as identity primary key,
  ma_phong bigint not null references public.phong(ma_phong) on delete cascade,
  duong_dan_cong_khai text not null,
  la_anh_bia boolean not null default false,
  thu_tu_hien_thi integer not null default 0 check (thu_tu_hien_thi >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index uq_hinh_anh_phong_anh_bia
on public.hinh_anh_phong(ma_phong)
where la_anh_bia = true;

create table public.tai_san_phong (
  ma_tai_san bigint generated by default as identity primary key,
  ma_phong bigint not null references public.phong(ma_phong) on delete cascade,
  ma_tai_san_hien_thi varchar(50) not null,
  ten_tai_san varchar(255) not null,
  danh_muc varchar(100) not null,
  muc_boi_thuong_mac_dinh numeric(14,2) not null default 0 check (muc_boi_thuong_mac_dinh >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_tai_san_phong_ma_hien_thi unique (ma_phong, ma_tai_san_hien_thi)
);

-- =========================================================
-- 2) FLOW 1 - YEU CAU THUE / DAT COC
-- =========================================================

create table public.yeu_cau_thue (
  ma_yeu_cau_thue bigint generated by default as identity primary key,
  ma_ho_so_khach_hang bigint not null references public.ho_so(ma_ho_so) on delete restrict,
  ma_ho_so_nhan_vien_phu_trach bigint references public.ho_so(ma_ho_so) on delete set null,
  loai_muc_tieu varchar(20) not null,
  ma_phong bigint references public.phong(ma_phong) on delete set null,
  ma_giuong bigint references public.giuong(ma_giuong) on delete set null,
  ngay_du_kien_vao_o date not null,
  gia_thue_thang numeric(14,2) not null default 0 check (gia_thue_thang >= 0),
  so_tien_dat_coc numeric(14,2) not null default 0 check (so_tien_dat_coc >= 0),
  trang_thai varchar(50) not null default 'MOI_TAO',
  checkoutUrl text,
  paymentLinkId text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_yct_loai_muc_tieu check (loai_muc_tieu in ('PHONG', 'GIUONG')),
  constraint chk_yct_target check (
    (loai_muc_tieu = 'PHONG' and ma_phong is not null)
    or
    (loai_muc_tieu = 'GIUONG' and ma_giuong is not null)
  )
);

create table public.nhat_ky_yeu_cau_thue (
  ma_nhat_ky bigint generated by default as identity primary key,
  ma_yeu_cau_thue bigint not null references public.yeu_cau_thue(ma_yeu_cau_thue) on delete cascade,
  trang_thai_cu varchar(50),
  trang_thai_moi varchar(50) not null,
  ma_ho_so_nguoi_thuc_hien bigint not null references public.ho_so(ma_ho_so) on delete restrict,
  ghi_chu text,
  created_at timestamptz not null default now()
);

create table public.giu_cho_tam (
  ma_giu_cho_tam bigint generated by default as identity primary key,
  ma_yeu_cau_thue bigint not null references public.yeu_cau_thue(ma_yeu_cau_thue) on delete cascade,
  loai_muc_tieu varchar(20) not null,
  ma_phong bigint references public.phong(ma_phong) on delete set null,
  ma_giuong bigint references public.giuong(ma_giuong) on delete set null,
  trang_thai varchar(50) not null default 'DANG_GIU',
  thoi_gian_het_han timestamptz not null,
  ly_do_huy_giu_cho text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_giu_cho_loai_muc_tieu check (loai_muc_tieu in ('PHONG', 'GIUONG')),
  constraint chk_giu_cho_target check (
    (loai_muc_tieu = 'PHONG' and ma_phong is not null)
    or
    (loai_muc_tieu = 'GIUONG' and ma_giuong is not null)
  ),
  checkoutUrl text,
  paymentLinkid text
);

-- =========================================================
-- 3) FLOW 2 - HOP DONG / HOA DON / THANH TOAN
-- =========================================================

create table public.hop_dong (
  ma_hop_dong bigint generated by default as identity primary key,
  ma_yeu_cau_thue bigint not null unique references public.yeu_cau_thue(ma_yeu_cau_thue) on delete restrict,
  ma_ho_so_khach_hang bigint not null references public.ho_so(ma_ho_so) on delete restrict,
  loai_muc_tieu varchar(20) not null,
  ma_phong bigint references public.phong(ma_phong) on delete set null,
  ma_giuong bigint references public.giuong(ma_giuong) on delete set null,
  ngay_vao_o date not null,
  gia_thue_co_ban_thang numeric(14,2) not null default 0 check (gia_thue_co_ban_thang >= 0),
  so_tien_dat_coc_bao_dam numeric(14,2) not null default 0 check (so_tien_dat_coc_bao_dam >= 0),
  trang_thai varchar(50) not null default 'CHO_LAP_KHOAN_THU_DAU',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_hop_dong_loai_muc_tieu check (loai_muc_tieu in ('PHONG', 'GIUONG')),
  constraint chk_hop_dong_target check (
    (loai_muc_tieu = 'PHONG' and ma_phong is not null)
    or
    (loai_muc_tieu = 'GIUONG' and (ma_giuong is not null or ma_phong is not null))
  )
);

create table public.hoa_don (
  ma_hoa_don bigint generated by default as identity primary key,
  ma_yeu_cau_thue bigint references public.yeu_cau_thue(ma_yeu_cau_thue) on delete set null,
  ma_hop_dong bigint references public.hop_dong(ma_hop_dong) on delete set null,
  loai_hoa_don varchar(50) not null,
  trang_thai varchar(50) not null default 'CHO_THANH_TOAN',
  tong_so_tien numeric(14,2) not null default 0 check (tong_so_tien >= 0),
  so_tien_da_thanh_toan numeric(14,2) not null default 0 check (so_tien_da_thanh_toan >= 0),
  ma_tai_khoan_ngan_hang varchar(100),
  ma_tham_chieu_qr varchar(100),
  ngay_lap date not null default current_date,
  ngay_den_han date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_hoa_don_nguon check (
    ma_yeu_cau_thue is not null or ma_hop_dong is not null
  ),
  constraint chk_hoa_don_tien check (
    so_tien_da_thanh_toan <= tong_so_tien
  )
);

create unique index uq_hoa_don_ma_tham_chieu_qr
on public.hoa_don(ma_tham_chieu_qr)
where ma_tham_chieu_qr is not null;

create table public.thanh_toan (
  ma_thanh_toan bigint generated by default as identity primary key,
  ma_hoa_don bigint not null references public.hoa_don(ma_hoa_don) on delete cascade,
  phuong_thuc varchar(50) not null,
  trang_thai varchar(50) not null default 'CHO_XAC_NHAN',
  so_tien numeric(14,2) not null check (so_tien > 0),
  ma_giao_dich varchar(100),
  ten_nguoi_thanh_toan varchar(150),
  thoi_gian_thanh_toan timestamptz,
  thoi_gian_xac_nhan timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index uq_thanh_toan_ma_giao_dich
on public.thanh_toan(ma_giao_dich)
where ma_giao_dich is not null;

create table public.bien_lai (
  ma_bien_lai bigint generated by default as identity primary key,
  ma_thanh_toan bigint not null references public.thanh_toan(ma_thanh_toan) on delete restrict,
  ma_hoa_don bigint not null references public.hoa_don(ma_hoa_don) on delete restrict,
  so_tien numeric(14,2) not null check (so_tien > 0),
  so_bien_lai varchar(100) not null unique,
  thoi_gian_lap timestamptz not null default now(),
  ma_ho_so_nguoi_lap bigint not null references public.ho_so(ma_ho_so) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.phan_bo_hop_dong (
  ma_phan_bo bigint generated by default as identity primary key,
  ma_hop_dong bigint not null references public.hop_dong(ma_hop_dong) on delete cascade,
  loai_muc_tieu varchar(20) not null,
  ma_phong bigint references public.phong(ma_phong) on delete set null,
  ma_giuong bigint references public.giuong(ma_giuong) on delete set null,
  ngay_bat_dau date not null,
  ngay_ket_thuc date,
  trang_thai varchar(50) not null default 'HIEU_LUC',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_phan_bo_loai_muc_tieu check (loai_muc_tieu in ('PHONG', 'GIUONG')),
  constraint chk_phan_bo_target check (
    (loai_muc_tieu = 'PHONG' and ma_phong is not null)
    or
    (loai_muc_tieu = 'GIUONG' and ma_giuong is not null)
  ),
  constraint chk_phan_bo_ngay check (
    ngay_ket_thuc is null or ngay_ket_thuc >= ngay_bat_dau
  )
);

create table public.khoan_thu_hop_dong (
  ma_khoan_thu bigint generated by default as identity primary key,
  ma_hop_dong bigint not null references public.hop_dong(ma_hop_dong) on delete cascade,
  giai_doan_phat_sinh varchar(50) not null,
  danh_muc varchar(100) not null,
  mo_ta text,
  so_tien numeric(14,2) not null default 0 check (so_tien >= 0),
  trang_thai_lap_hoa_don varchar(50) not null default 'CHUA_LAP',
  ma_hoa_don_da_lap bigint references public.hoa_don(ma_hoa_don) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chi_tiet_hoa_don (
  ma_chi_tiet_hoa_don bigint generated by default as identity primary key,
  ma_hoa_don bigint not null references public.hoa_don(ma_hoa_don) on delete cascade,
  ma_khoan_thu bigint references public.khoan_thu_hop_dong(ma_khoan_thu) on delete set null,
  danh_muc varchar(100) not null,
  mo_ta text,
  so_luong numeric(12,2) not null default 1 check (so_luong > 0),
  don_gia numeric(14,2) not null default 0 check (don_gia >= 0),
  thanh_tien numeric(14,2) not null default 0 check (thanh_tien >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================================================
-- 4) FLOW 3 - TRA PHONG / DOI SOAT / HOAN COC
-- =========================================================

create table public.yeu_cau_tra_phong (
  ma_yeu_cau_tra_phong bigint generated by default as identity primary key,
  ma_hop_dong bigint not null references public.hop_dong(ma_hop_dong) on delete restrict,
  ma_ho_so_khach_hang bigint not null references public.ho_so(ma_ho_so) on delete restrict,
  ngay_yeu_cau_tra_phong date not null,
  gio_ban_giao time,
  ly_do text,
  trang_thai varchar(50) not null default 'CHO_XU_LY',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.bien_ban_kiem_tra (
  ma_bien_ban_kiem_tra bigint generated by default as identity primary key,
  ma_yeu_cau_tra_phong bigint not null references public.yeu_cau_tra_phong(ma_yeu_cau_tra_phong) on delete cascade,
  ma_hop_dong bigint not null references public.hop_dong(ma_hop_dong) on delete restrict,
  ma_ho_so_nguoi_kiem_tra bigint not null references public.ho_so(ma_ho_so) on delete restrict,
  thoi_gian_kiem_tra timestamptz not null default now(),
  tong_uoc_tinh_khau_tru numeric(14,2) not null default 0 check (tong_uoc_tinh_khau_tru >= 0),
  trang_thai varchar(50) not null default 'DA_KIEM_TRA',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chi_tiet_kiem_tra (
  ma_chi_tiet_kiem_tra bigint generated by default as identity primary key,
  ma_bien_ban_kiem_tra bigint not null references public.bien_ban_kiem_tra(ma_bien_ban_kiem_tra) on delete cascade,
  ma_tai_san_phong bigint references public.tai_san_phong(ma_tai_san) on delete set null,
  ten_tai_san varchar(255) not null,
  tinh_trang varchar(100) not null,
  so_tien_boi_thuong numeric(14,2) not null default 0 check (so_tien_boi_thuong >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.doi_soat_tai_chinh (
  ma_doi_soat bigint generated by default as identity primary key,
  ma_hop_dong bigint not null references public.hop_dong(ma_hop_dong) on delete restrict,
  so_tien_dat_coc_ban_dau numeric(14,2) not null default 0 check (so_tien_dat_coc_ban_dau >= 0),
  so_tien_hoan_lai numeric(14,2) not null default 0 check (so_tien_hoan_lai >= 0),
  so_tien_can_thanh_toan_them numeric(14,2) not null default 0 check (so_tien_can_thanh_toan_them >= 0),
  trang_thai varchar(50) not null default 'CHO_CHOT',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chi_tiet_doi_soat_tai_chinh (
  ma_chi_tiet_doi_soat bigint generated by default as identity primary key,
  ma_doi_soat bigint not null references public.doi_soat_tai_chinh(ma_doi_soat) on delete cascade,
  danh_muc varchar(100) not null,
  huong_giao_dich varchar(20) not null,
  loai_nguon varchar(50),
  ma_nguon bigint,
  so_tien numeric(14,2) not null check (so_tien >= 0),
  mo_ta text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_ct_dstc_huong check (huong_giao_dich in ('THU', 'CHI'))
);

create table public.phieu_thanh_toan_phat_sinh (
  ma_phieu_tt_phat_sinh bigint generated by default as identity primary key,
  ma_doi_soat bigint not null references public.doi_soat_tai_chinh(ma_doi_soat) on delete cascade,
  ma_hop_dong bigint not null references public.hop_dong(ma_hop_dong) on delete restrict,
  so_tien_thanh_toan numeric(14,2) not null check (so_tien_thanh_toan >= 0),
  trang_thai varchar(50) not null default 'CHO_THANH_TOAN',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.phieu_hoan_coc (
  ma_phieu_hoan_coc bigint generated by default as identity primary key,
  ma_doi_soat bigint not null references public.doi_soat_tai_chinh(ma_doi_soat) on delete cascade,
  ma_hop_dong bigint not null references public.hop_dong(ma_hop_dong) on delete restrict,
  so_tien_hoan numeric(14,2) not null check (so_tien_hoan >= 0),
  ten_nguoi_nhan varchar(150) not null,
  trang_thai varchar(50) not null default 'CHO_HOAN',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================================================
-- 5) LOG VAN HANH
-- =========================================================

create table public.nhat_ky_he_thong (
  ma_nhat_ky_he_thong bigint generated by default as identity primary key,
  ten_bang varchar(100) not null,
  ma_ban_ghi bigint not null,
  hanh_dong varchar(50) not null,
  ma_ho_so_nguoi_thuc_hien bigint references public.ho_so(ma_ho_so) on delete set null,
  thoi_gian_tao timestamptz not null default now(),
  ghi_chu text
);

-- =========================================================
-- 6) INDEXES
-- =========================================================

create index idx_tang_ma_toa on public.tang(ma_toa);

create index idx_phong_ma_toa on public.phong(ma_toa);
create index idx_phong_ma_tang on public.phong(ma_tang);
create index idx_phong_trang_thai on public.phong(trang_thai);

create index idx_giuong_ma_phong on public.giuong(ma_phong);
create index idx_giuong_trang_thai on public.giuong(trang_thai);

create index idx_hinh_anh_phong_ma_phong on public.hinh_anh_phong(ma_phong);
create index idx_tai_san_phong_ma_phong on public.tai_san_phong(ma_phong);

create index idx_ho_so_vai_tro on public.ho_so(vai_tro);
create index idx_ho_so_so_dien_thoai on public.ho_so(so_dien_thoai);

create index idx_yct_khach_hang on public.yeu_cau_thue(ma_ho_so_khach_hang);
create index idx_yct_nhan_vien on public.yeu_cau_thue(ma_ho_so_nhan_vien_phu_trach);
create index idx_yct_ma_phong on public.yeu_cau_thue(ma_phong);
create index idx_yct_ma_giuong on public.yeu_cau_thue(ma_giuong);
create index idx_yct_trang_thai on public.yeu_cau_thue(trang_thai);

create index idx_nk_yct_ma_yct on public.nhat_ky_yeu_cau_thue(ma_yeu_cau_thue);

create index idx_giu_cho_ma_yct on public.giu_cho_tam(ma_yeu_cau_thue);
create index idx_giu_cho_het_han on public.giu_cho_tam(thoi_gian_het_han);

create index idx_hop_dong_ma_ho_so_khach_hang on public.hop_dong(ma_ho_so_khach_hang);
create index idx_hop_dong_ma_phong on public.hop_dong(ma_phong);
create index idx_hop_dong_ma_giuong on public.hop_dong(ma_giuong);
create index idx_hop_dong_trang_thai on public.hop_dong(trang_thai);

create index idx_hoa_don_ma_yct on public.hoa_don(ma_yeu_cau_thue);
create index idx_hoa_don_ma_hd on public.hoa_don(ma_hop_dong);
create index idx_hoa_don_trang_thai on public.hoa_don(trang_thai);
create index idx_hoa_don_ngay_den_han on public.hoa_don(ngay_den_han);

create index idx_thanh_toan_ma_hoa_don on public.thanh_toan(ma_hoa_don);
create index idx_thanh_toan_trang_thai on public.thanh_toan(trang_thai);

create index idx_bien_lai_ma_hoa_don on public.bien_lai(ma_hoa_don);
create index idx_bien_lai_ma_thanh_toan on public.bien_lai(ma_thanh_toan);

create index idx_phan_bo_ma_hop_dong on public.phan_bo_hop_dong(ma_hop_dong);

create index idx_khoan_thu_ma_hop_dong on public.khoan_thu_hop_dong(ma_hop_dong);
create index idx_khoan_thu_ma_hoa_don_da_lap on public.khoan_thu_hop_dong(ma_hoa_don_da_lap);

create index idx_cthd_ma_hoa_don on public.chi_tiet_hoa_don(ma_hoa_don);
create index idx_cthd_ma_khoan_thu on public.chi_tiet_hoa_don(ma_khoan_thu);

create index idx_yctp_ma_hop_dong on public.yeu_cau_tra_phong(ma_hop_dong);

create index idx_bbkt_ma_yctp on public.bien_ban_kiem_tra(ma_yeu_cau_tra_phong);
create index idx_bbkt_ma_hop_dong on public.bien_ban_kiem_tra(ma_hop_dong);

create index idx_ctkt_ma_bbkt on public.chi_tiet_kiem_tra(ma_bien_ban_kiem_tra);

create index idx_dstc_ma_hop_dong on public.doi_soat_tai_chinh(ma_hop_dong);

create index idx_ctdstc_ma_doi_soat on public.chi_tiet_doi_soat_tai_chinh(ma_doi_soat);

create index idx_pttps_ma_doi_soat on public.phieu_thanh_toan_phat_sinh(ma_doi_soat);
create index idx_pttps_ma_hop_dong on public.phieu_thanh_toan_phat_sinh(ma_hop_dong);

create index idx_phc_ma_doi_soat on public.phieu_hoan_coc(ma_doi_soat);
create index idx_phc_ma_hop_dong on public.phieu_hoan_coc(ma_hop_dong);

create index idx_nhat_ky_he_thong_nguoi on public.nhat_ky_he_thong(ma_ho_so_nguoi_thuc_hien);
create index idx_nhat_ky_he_thong_bang_ban_ghi on public.nhat_ky_he_thong(ten_bang, ma_ban_ghi);

-- =========================================================
-- 7) UPDATED_AT TRIGGERS
-- =========================================================

create trigger trg_ho_so_updated_at
before update on public.ho_so
for each row execute function public.set_updated_at();

create trigger trg_toa_updated_at
before update on public.toa
for each row execute function public.set_updated_at();

create trigger trg_tang_updated_at
before update on public.tang
for each row execute function public.set_updated_at();

create trigger trg_phong_updated_at
before update on public.phong
for each row execute function public.set_updated_at();

create trigger trg_giuong_updated_at
before update on public.giuong
for each row execute function public.set_updated_at();

create trigger trg_hinh_anh_phong_updated_at
before update on public.hinh_anh_phong
for each row execute function public.set_updated_at();

create trigger trg_tai_san_phong_updated_at
before update on public.tai_san_phong
for each row execute function public.set_updated_at();

create trigger trg_yct_updated_at
before update on public.yeu_cau_thue
for each row execute function public.set_updated_at();

create trigger trg_giu_cho_tam_updated_at
before update on public.giu_cho_tam
for each row execute function public.set_updated_at();

create trigger trg_hop_dong_updated_at
before update on public.hop_dong
for each row execute function public.set_updated_at();

create trigger trg_hoa_don_updated_at
before update on public.hoa_don
for each row execute function public.set_updated_at();

create trigger trg_thanh_toan_updated_at
before update on public.thanh_toan
for each row execute function public.set_updated_at();

create trigger trg_bien_lai_updated_at
before update on public.bien_lai
for each row execute function public.set_updated_at();

create trigger trg_phan_bo_hop_dong_updated_at
before update on public.phan_bo_hop_dong
for each row execute function public.set_updated_at();

create trigger trg_khoan_thu_hop_dong_updated_at
before update on public.khoan_thu_hop_dong
for each row execute function public.set_updated_at();

create trigger trg_chi_tiet_hoa_don_updated_at
before update on public.chi_tiet_hoa_don
for each row execute function public.set_updated_at();

create trigger trg_yctp_updated_at
before update on public.yeu_cau_tra_phong
for each row execute function public.set_updated_at();

create trigger trg_bbkt_updated_at
before update on public.bien_ban_kiem_tra
for each row execute function public.set_updated_at();

create trigger trg_ctkt_updated_at
before update on public.chi_tiet_kiem_tra
for each row execute function public.set_updated_at();

create trigger trg_dstc_updated_at
before update on public.doi_soat_tai_chinh
for each row execute function public.set_updated_at();

create trigger trg_ctdstc_updated_at
before update on public.chi_tiet_doi_soat_tai_chinh
for each row execute function public.set_updated_at();

create trigger trg_pttps_updated_at
before update on public.phieu_thanh_toan_phat_sinh
for each row execute function public.set_updated_at();

create trigger trg_phc_updated_at
before update on public.phieu_hoan_coc
for each row execute function public.set_updated_at();

-- =========================================================
-- =========================================================
-- 8) SUPABASE AUTH -> AUTO CREATE PROFILE
-- =========================================================

-- Tao bảng profiles (phụ trợ)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone default now(),
  full_name text,
  phone text,
  avatar_url text,
  role text default 'customer'
);

alter table public.profiles enable row level security;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- 1. Insert vào ho_so (Bảng chính của App)
  insert into public.ho_so (
    ma_nguoi_dung_xac_thuc,
    vai_tro,
    ho_ten,
    email,
    so_dien_thoai
  )
  values (
    new.id,
    'KHACH_HANG',
    coalesce(new.raw_user_meta_data ->> 'ho_ten', new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, 'user'), '@', 1)),
    new.email,
    new.raw_user_meta_data ->> 'phone'
  )
  on conflict (ma_nguoi_dung_xac_thuc) do nothing;

  -- 2. Insert vào profiles (Bảng phụ trợ)
  insert into public.profiles (id, full_name, phone)
  values (
    new.id, 
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'ho_ten'), 
    new.raw_user_meta_data->>'phone'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

-- =========================================================
-- 9) STORAGE BUCKETS & POLICIES
-- =========================================================

-- 1. Tạo bucket 'profiles' nếu chưa có và bật chế độ công khai
insert into storage.buckets (id, name, public)
values ('profiles', 'profiles', true)
on conflict (id) do nothing;

-- 2. Cho phép mọi người xem ảnh trong bucket 'profiles'
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'profiles' );

-- 3. Cho phép người dùng đã đăng nhập tải ảnh lên
create policy "Authenticated Upload"
on storage.objects for insert
with check ( bucket_id = 'profiles' and auth.role() = 'authenticated' );

commit;

BEGIN;

ALTER TABLE public.yeu_cau_thue
  ADD COLUMN IF NOT EXISTS so_luong_giuong_dat integer NOT NULL DEFAULT 1;

ALTER TABLE public.yeu_cau_thue
  DROP CONSTRAINT IF EXISTS chk_yct_target;

ALTER TABLE public.yeu_cau_thue
  ADD CONSTRAINT chk_yct_target CHECK (
    (loai_muc_tieu = 'PHONG' AND ma_phong IS NOT NULL)
    OR
    (loai_muc_tieu = 'GIUONG' AND (ma_giuong IS NOT NULL OR ma_phong IS NOT NULL))
  );

CREATE INDEX IF NOT EXISTS idx_giu_cho_tam_ma_giuong_status
  ON public.giu_cho_tam(ma_giuong, trang_thai, thoi_gian_het_han);

CREATE INDEX IF NOT EXISTS idx_giu_cho_tam_ma_phong_status
  ON public.giu_cho_tam(ma_phong, trang_thai, thoi_gian_het_han);

CREATE UNIQUE INDEX IF NOT EXISTS uq_giu_cho_tam_active_bed
  ON public.giu_cho_tam(ma_giuong)
  WHERE ma_giuong IS NOT NULL
    AND trang_thai IN ('DANG_GIU', 'DA_XAC_NHAN_COC');

CREATE UNIQUE INDEX IF NOT EXISTS uq_giu_cho_tam_active_room
  ON public.giu_cho_tam(ma_phong)
  WHERE ma_phong IS NOT NULL
    AND loai_muc_tieu = 'PHONG'
    AND trang_thai IN ('DANG_GIU', 'DA_XAC_NHAN_COC');

CREATE UNIQUE INDEX IF NOT EXISTS uq_hoa_don_dat_coc_per_request
ON public.hoa_don(ma_yeu_cau_thue, loai_hoa_don)
WHERE ma_yeu_cau_thue IS NOT NULL
  AND loai_hoa_don = 'DAT_COC';

CREATE UNIQUE INDEX IF NOT EXISTS uq_phieu_hoan_coc_per_doi_soat
ON public.phieu_hoan_coc(ma_doi_soat);

CREATE UNIQUE INDEX IF NOT EXISTS uq_phieu_tt_phat_sinh_per_doi_soat
ON public.phieu_thanh_toan_phat_sinh(ma_doi_soat);

CREATE OR REPLACE FUNCTION public.create_rental_request_with_holds(
  p_ma_ho_so_khach_hang  bigint,
  p_loai_muc_tieu        varchar,
  p_ma_phong             bigint,
  p_selected_beds        bigint[],
  p_ngay_du_kien_vao_o   date,
  p_gia_thue_thang       numeric,
  p_so_tien_dat_coc      numeric,
  p_trang_thai           varchar DEFAULT 'DANG_XU_LY',
  p_thoi_gian_het_han    timestamptz DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_yct_id         bigint;
  v_bed_count      integer;
  v_bed_record     record;
  v_hold_expiry    timestamptz;
  v_conflict_count integer;
  v_result         jsonb;
BEGIN
  v_hold_expiry := COALESCE(p_thoi_gian_het_han, NOW() + INTERVAL '24 hours');
  v_bed_count := COALESCE(array_length(p_selected_beds, 1), 0);

  IF p_loai_muc_tieu = 'GIUONG' AND v_bed_count = 0 THEN
    RAISE EXCEPTION 'GIUONG request requires at least 1 bed in p_selected_beds';
  END IF;

  IF p_loai_muc_tieu = 'PHONG' AND v_bed_count = 0 THEN
    RAISE EXCEPTION 'PHONG request requires beds in p_selected_beds';
  END IF;

  IF v_bed_count > 0 THEN
    PERFORM 1
    FROM unnest(p_selected_beds) AS bed_id
    WHERE NOT EXISTS (
      SELECT 1 FROM public.giuong
      WHERE ma_giuong = bed_id AND ma_phong = p_ma_phong
    );
    IF FOUND THEN
      RAISE EXCEPTION 'One or more beds do not belong to room %', p_ma_phong;
    END IF;
  END IF;

  IF v_bed_count > 0 THEN
    FOR v_bed_record IN
      SELECT g.ma_giuong, g.ma_giuong_hien_thi, g.trang_thai
      FROM public.giuong g
      WHERE g.ma_giuong = ANY(p_selected_beds)
        AND g.trang_thai NOT IN ('TRONG', 'CON_TRONG')
    LOOP
      RAISE EXCEPTION 'Bed % (%) is not available (status: %)',
        v_bed_record.ma_giuong, v_bed_record.ma_giuong_hien_thi, v_bed_record.trang_thai;
    END LOOP;
  END IF;

  IF v_bed_count > 0 THEN
    UPDATE public.giu_cho_tam
    SET trang_thai = 'HET_HAN',
        updated_at = NOW()
    WHERE trang_thai = 'DANG_GIU'
      AND thoi_gian_het_han IS NOT NULL
      AND thoi_gian_het_han < NOW()
      AND ma_giuong = ANY(p_selected_beds);

    SELECT count(*) INTO v_conflict_count
    FROM public.giu_cho_tam
    WHERE ma_giuong = ANY(p_selected_beds)
      AND trang_thai IN ('DANG_GIU', 'DA_XAC_NHAN_COC')
      AND (thoi_gian_het_han IS NULL OR thoi_gian_het_han > NOW());
    IF v_conflict_count > 0 THEN
      RAISE EXCEPTION 'One or more beds already have active holds (% conflicts)', v_conflict_count;
    END IF;
  END IF;

  INSERT INTO public.yeu_cau_thue (
    ma_ho_so_khach_hang,
    loai_muc_tieu,
    ma_phong,
    ma_giuong,
    so_luong_giuong_dat,
    ngay_du_kien_vao_o,
    gia_thue_thang,
    so_tien_dat_coc,
    trang_thai
  ) VALUES (
    p_ma_ho_so_khach_hang,
    p_loai_muc_tieu,
    p_ma_phong,
    CASE WHEN v_bed_count = 1 AND p_loai_muc_tieu = 'GIUONG'
         THEN p_selected_beds[1]
         ELSE NULL
    END,
    v_bed_count,
    p_ngay_du_kien_vao_o,
    p_gia_thue_thang,
    p_so_tien_dat_coc,
    p_trang_thai
  )
  RETURNING ma_yeu_cau_thue INTO v_yct_id;

  IF v_bed_count > 0 THEN
    INSERT INTO public.giu_cho_tam (
      ma_yeu_cau_thue,
      loai_muc_tieu,
      ma_phong,
      ma_giuong,
      trang_thai,
      thoi_gian_het_han
    )
    SELECT
      v_yct_id,
      'GIUONG',
      p_ma_phong,
      bed_id,
      'DANG_GIU',
      v_hold_expiry
    FROM unnest(p_selected_beds) AS bed_id;
  END IF;

  SELECT to_jsonb(yct.*) INTO v_result
  FROM public.yeu_cau_thue yct
  WHERE yct.ma_yeu_cau_thue = v_yct_id;

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.expire_stale_holds()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_expired_hold_count integer := 0;
  v_expired_request_count integer := 0;
BEGIN
  WITH expired AS (
    UPDATE public.giu_cho_tam
    SET trang_thai = 'HET_HAN',
        updated_at = NOW()
    WHERE trang_thai = 'DANG_GIU'
      AND thoi_gian_het_han < NOW()
    RETURNING ma_yeu_cau_thue
  )
  SELECT count(*) INTO v_expired_hold_count FROM expired;

  WITH requests_to_expire AS (
    SELECT DISTINCT gct.ma_yeu_cau_thue
    FROM public.giu_cho_tam gct
    JOIN public.yeu_cau_thue yct ON yct.ma_yeu_cau_thue = gct.ma_yeu_cau_thue
    WHERE yct.trang_thai IN ('DANG_XU_LY', 'MOI_TAO', 'CHO_THANH_TOAN')
      AND NOT EXISTS (
        SELECT 1 FROM public.giu_cho_tam gct2
        WHERE gct2.ma_yeu_cau_thue = gct.ma_yeu_cau_thue
          AND gct2.trang_thai IN ('DANG_GIU', 'DA_XAC_NHAN_COC')
      )
  ),
  updated_requests AS (
    UPDATE public.yeu_cau_thue
    SET trang_thai = 'QUA_HAN',
        updated_at = NOW()
    WHERE ma_yeu_cau_thue IN (SELECT ma_yeu_cau_thue FROM requests_to_expire)
    RETURNING ma_yeu_cau_thue
  )
  SELECT count(*) INTO v_expired_request_count FROM updated_requests;

  RETURN jsonb_build_object(
    'expired_holds', v_expired_hold_count,
    'expired_requests', v_expired_request_count
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.confirm_rental_payment(
  p_ma_yeu_cau_thue bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result jsonb;
  v_current_status varchar;
BEGIN
  SELECT trang_thai INTO v_current_status
  FROM public.yeu_cau_thue
  WHERE ma_yeu_cau_thue = p_ma_yeu_cau_thue;

  IF v_current_status IS NULL THEN
    RAISE EXCEPTION 'Request % not found', p_ma_yeu_cau_thue;
  END IF;

  IF v_current_status NOT IN ('DANG_XU_LY', 'MOI_TAO', 'CHO_THANH_TOAN') THEN
    RAISE EXCEPTION 'Cannot confirm payment - request is in status %', v_current_status;
  END IF;

  UPDATE public.yeu_cau_thue
  SET trang_thai = 'DA_COC',
      updated_at = NOW()
  WHERE ma_yeu_cau_thue = p_ma_yeu_cau_thue;

  UPDATE public.giu_cho_tam
  SET trang_thai = 'DA_XAC_NHAN_COC',
      updated_at = NOW()
  WHERE ma_yeu_cau_thue = p_ma_yeu_cau_thue
    AND trang_thai = 'DANG_GIU';

  SELECT to_jsonb(yct.*) INTO v_result
  FROM public.yeu_cau_thue yct
  WHERE yct.ma_yeu_cau_thue = p_ma_yeu_cau_thue;

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_room_status_by_beds(
  p_ma_phong bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_room_record RECORD;
  v_total_beds integer;
  v_rented_beds integer;
  v_is_dorm boolean;
  v_new_status varchar;
  v_result jsonb;
BEGIN
  SELECT
    ma_phong,
    loai_phong,
    (loai_phong = 'PHONG_CHUNG') as is_dorm,
    trang_thai
  INTO v_room_record
  FROM public.phong
  WHERE ma_phong = p_ma_phong;

  IF v_room_record.ma_phong IS NULL THEN
    RAISE EXCEPTION 'Room % not found', p_ma_phong;
  END IF;

  v_is_dorm := v_room_record.is_dorm;

  SELECT COUNT(*) INTO v_total_beds
  FROM public.giuong
  WHERE ma_phong = p_ma_phong;

  IF v_total_beds = 0 THEN
    RETURN to_jsonb(v_room_record);
  END IF;

  IF v_is_dorm THEN
    SELECT COUNT(*) INTO v_rented_beds
    FROM public.giuong
    WHERE ma_phong = p_ma_phong
      AND trang_thai IN ('DA_THUE', 'DANG_GIU');

    IF v_rented_beds >= v_total_beds THEN
      v_new_status := 'DAY';
    ELSIF v_rented_beds > 0 THEN
      v_new_status := 'SAP_DAY';
    ELSE
      v_new_status := 'TRONG';
    END IF;

    IF v_new_status != v_room_record.trang_thai THEN
      UPDATE public.phong
      SET trang_thai = v_new_status,
          updated_at = NOW()
      WHERE ma_phong = p_ma_phong;
    END IF;
  END IF;

  SELECT to_jsonb(p.*) INTO v_result
  FROM public.phong p
  WHERE p.ma_phong = p_ma_phong;

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.trigger_update_room_status_on_bed_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result jsonb;
BEGIN
  SELECT public.update_room_status_by_beds(NEW.ma_phong)
  INTO v_result;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_bed_status_update_room_status ON public.giuong;

CREATE TRIGGER trg_bed_status_update_room_status
AFTER UPDATE ON public.giuong
FOR EACH ROW
WHEN (OLD.trang_thai IS DISTINCT FROM NEW.trang_thai)
EXECUTE FUNCTION public.trigger_update_room_status_on_bed_change();

COMMIT;

-- =========================================================
-- 10) LEGACY STATUS CLEANUP
-- =========================================================

BEGIN;

UPDATE public.yeu_cau_thue
SET trang_thai = 'DA_XAC_NHAN',
    updated_at = now()
WHERE trang_thai = 'DA_DUYET';

UPDATE public.nhat_ky_yeu_cau_thue
SET trang_thai_cu = 'DA_XAC_NHAN'
WHERE trang_thai_cu = 'DA_DUYET';

UPDATE public.nhat_ky_yeu_cau_thue
SET trang_thai_moi = 'DA_XAC_NHAN'
WHERE trang_thai_moi = 'DA_DUYET';

UPDATE public.nhat_ky_he_thong
SET hanh_dong = 'XAC_NHAN_YEU_CAU'
WHERE hanh_dong = 'DUYET_YEU_CAU';

UPDATE public.yeu_cau_tra_phong
SET trang_thai = 'DA_THANH_LY',
    updated_at = now()
WHERE trang_thai = 'HOAN_TAT';

COMMIT;
